### ISSUE TITLE
Multiple VIRTUAL_HOST

### ISSUE THREAD

**Issue by avidsapp** [kid/nginx-letsencrypt-proxy#1]
Successfully working with one virtual host, but not multiple.

Passes LE:

```
docker run -it --rm \
  --name letsencrypt \
  --volumes-from letsencrypt-data \
  --volumes-from nginx \
  quay.io/letsencrypt/letsencrypt \
  certonly \
  --webroot-path /var/www/letsencrypt \
  -a webroot \
  --text \
  --agree-tos \
  --renew-by-default \
  --email foo@bar.com \
  -d bar.com,foo.bar.com

or

  -d bar.com \
  -d foo.bar.com \
```

`VIRTUAL_HOST=bar.com,foo.bar.com` only works for bar.com when `CERT_NAME=bar.com` is added. Otherwise, it doesn't work.

**Comment by kid** [comment]
Fixed in #2 
Should support both scenario, i.e. if using `-d bar.com,foo.bar.com` use `CERT_NAME=bar.com`
