### ISSUE TITLE
Proxy-wide configuration

### ISSUE THREAD

**Issue by avidsapp** [kid/nginx-letsencrypt-proxy#3]
Can the proxy be configured [like jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy/blob/master/README.md#proxy-wide)?

**Comment by kid** [comment]
Not yet, but that is something I would like to support. I'm on vacation so it won't be before next week, but feel free to make a pull request in the meantime :)

**Comment by avidsapp** [comment]
Would love to, but outside my current grasp. Can the docker run commands be translated to docker compose?
