### ISSUE TITLE
Auto-update nginx

### ISSUE THREAD

**Issue by avidsapp** [kid/nginx-letsencrypt-proxy#4]
After adding a second back-end container, both sites no longer work correctly and the second is referencing the first's database. Has to do with an nginx update error?

**Comment by kid** [comment]
Could you describe in more details your setup?
You have 2 web sites with one backend each, and you are trying to add a second backend node to one of the web sites? or is it something else?

I'm currently on vacation and won't have time to look it up before next week :)

**Comment by avidsapp** [comment]
My apologies for the confusion. I have multiple applications (websites) proxied. Each application has 3 containers. I spun up one app using the LE cert and it passed. When I added the second app, app #1's LE cert was unusable and the new container was pulling up app #1's LE cert with a domain mismatch.

I've reverted to [dmp1ce/nginx-proxy-letsencrypt](https://github.com/dmp1ce/nginx-proxy-letsencrypt). Feel free to close #3 and #4
